name: "CI"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: snok/install-poetry@v1.1.2
      with:
        version: 1.1.4
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv

    - name: Install Dependecies
      run: |
        poetry install

    - name: Run Tests
      run: |
        poetry run mypy ./wavelink-stubs
